language: rust
os:
  - linux
rust:
  - stable
  - nightly
matrix:
  fast_finish: true
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
jobs:
  allow_failures:
    - rust: nightly
script:
  - rustc --version --verbose
  - cargo --version --verbose
  - cargo build --verbose
  - cargo test --verbose
