language: rust
os:
  - linux
addons:
  apt:
    packages:
      - musl-tools
matrix:
  fast_finish: true
  include:
    - rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
    - rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    - rust: nightly
      env: TARGET=x86_64-unknown-linux-musl
  allow_failures:
    - rust: nightly
install: ci/install.sh
script: ci/travis.sh
