[package]
name = "watch"
version = "0.3.0"
authors = ["thyrc <thyrc@users.noreply.github.com>"]
description = "Poor man's intrusion detection"
license = "MIT"
edition = "2018"

[dependencies]
inotify = "0.8"
